[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
